### ISSUE TITLE
Session not found when using FRONT_CHANNEL SLO with jboss undertow

### ISSUE THREAD

**Issue by kalmykov-sergey** [apereo/java-cas-client#145]
Order of actions: session invalidation, then response.sendRedirect() is not supported by io.undertow:

```
2015-12-03 17:52:01,592 WARN  [org.jasig.cas.client.util.CommonUtils] (default task-43) UT000010: Session not found WGFGOBPKUbDCZ8kekzv4nVTBv80pFaMCa6zAxxxi: java.lang.IllegalStateException: UT000010: Session not found WGFGOBPKUbDCZ8kekzv4nVTBv80pFaMCa6zAxxxi
    at io.undertow.server.session.InMemorySessionManager$SessionImpl.getAttribute(InMemorySessionManager.java:430)
    at io.undertow.servlet.spec.HttpSessionImpl.getAttribute(HttpSessionImpl.java:123)
    at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.saveContext(HttpSessionSecurityContextRepository.java:357)
    at org.springframework.security.web.context.SaveContextOnUpdateOrErrorResponseWrapper.onResponseCommitted(SaveContextOnUpdateOrErrorResponseWrapper.java:85)
    at org.springframework.security.web.context.OnCommittedResponseWrapper.doOnResponseCommitted(OnCommittedResponseWrapper.java:208)
    at org.springframework.security.web.context.OnCommittedResponseWrapper.sendRedirect(OnCommittedResponseWrapper.java:114)
    at org.jasig.cas.client.util.CommonUtils.sendRedirect(CommonUtils.java:470)
    at org.jasig.cas.client.session.SingleSignOutHandler.process(SingleSignOutHandler.java:217)
    at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:96)
```

For reverse actions order logout works correctly (SingleSignOutHandler):

```
else if (isFrontChannelLogoutRequest(request)) {
            logger.trace("Received a front channel logout request");
            // redirection url to the CAS server
            final String redirectionUrl = computeRedirectionToServer(request);
            if (redirectionUrl != null) {
                CommonUtils.sendRedirect(response, redirectionUrl);
            }
            destroySession(request);
            return false;

        }
```

**Comment by leleuj** [comment]
That's strange but I guess it's a specificity from Undertow: did you try the updated front logout (reverse order) with other application servers like Tomcat or Jetty? Just to be sure it still works (I hope so)
