### ISSUE TITLE
Null pointer exception with PROPERTY_FILE configuration

### ISSUE THREAD

**Issue by wrighting** [apereo/java-cas-client#174]
I'm trying to get the PROPERTY_FILE configuration strategy to work

In my web.xml I've got:
```
	<context-param>
		<param-name>configurationStrategy</param-name>
		<param-value>PROPERTY_FILE</param-value>
	</context-param>

	<context-param>
		<param-name>configFileLocation</param-name>
		<param-value>/etc/java-cas-client.properties</param-value>
	</context-param>

	<filter>
		<filter-name>CAS Authentication Filter</filter-name>
		<filter-class>org.jasig.cas.client.authentication.AuthenticationFilter</filter-class>
	</filter>
	<filter>
		<filter-name>CAS Validation Filter</filter-name>
		<filter-class>org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter</filter-class>
	</filter>
	<filter>
		<filter-name>CAS HttpServletRequest Wrapper Filter</filter-name>
		<filter-class>org.jasig.cas.client.util.HttpServletRequestWrapperFilter</filter-class>
	</filter>

```

I tried /etc/java-cas-client.properties with these values:
```
casServerLoginUrl=https://xxxx/cas/login
serverName=http://localhost:8080
ticketValidatorClass=org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter
```
(I ended up looking at the code to see the ticketValidatorClass property)

ReflectUtils.newInstance isn't happy because it doesn't like null as the args param
```
java.lang.NullPointerException
	at org.jasig.cas.client.util.ReflectUtils.newInstance(ReflectUtils.java:77)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.createNewTicketValidator(Cas20ProxyReceivingTicketValidationFilter.java:139)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.getTicketValidator(Cas20ProxyReceivingTicketValidationFilter.java:162)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.initInternal(AbstractTicketValidationFilter.java:140)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.initInternal(Cas20ProxyReceivingTicketValidationFilter.java:116)
	at org.jasig.cas.client.util.AbstractCasFilter.init(AbstractCasFilter.java:72)
```

So having a look at the code I thought I'd try this:
```
casServerLoginUrl=https://xxxx/cas/login
serverName=http://localhost:8080
ticketValidatorClass=org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter
casServerUrlPrefix=https://xxxx/cas/login
```

It gets further but fairly obviously this fails because the constructor doesn't take any args

```
SEVERE: Exception starting filter CAS Validation Filter
java.lang.IllegalArgumentException: Error creating new instance of class org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter
	at org.jasig.cas.client.util.ReflectUtils.newInstance(ReflectUtils.java:82)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.createNewTicketValidator(Cas20ProxyReceivingTicketValidationFilter.java:139)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.getTicketValidator(Cas20ProxyReceivingTicketValidationFilter.java:162)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.initInternal(AbstractTicketValidationFilter.java:140)
	at org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.initInternal(Cas20ProxyReceivingTicketValidationFilter.java:116)
	at org.jasig.cas.client.util.AbstractCasFilter.init(AbstractCasFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.jasig.cas.client.util.ReflectUtils.newInstance(ReflectUtils.java:80)
```

**Comment by battags** [comment]
Hi. Your question is best suited for the mailing list but I did notice that you assigned a ticket validation filter as the ticket validation. That's not going to work. You also should not need to specify one considering you chose a filter that will create one.

**Comment by wrighting** [comment]
I opened this as an issue because:

1) There's usually a nice error message rather than a null pointer exception when something is wrong so I thought you might like to improve the error handling here

2) I couldn't find anything in the docs/examples/tests to help with this configuration method so it would be good to add something

For reference it crashes earlier without the ticketValidatorClass property.

(It wasn't meant to be a question)
