### ISSUE TITLE
TicketValidationException: No principal was found in the response from the CAS server

### ISSUE THREAD

**Issue by wenchma** [apereo/java-cas-client#238]
I setup this java cas client for authN, the response ticket validation  throw exception:
```
org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.  
org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.
	at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:98) [cas-client-core-3.5.0.jar:3.5.0]
	at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:201) [cas-client-core-3.5.0.jar:3.5.0]
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:204) [cas-client-core-3.5.0.jar:3.5.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:92) [cas-client-core-3.5.0.jar:3.5.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.6]
	at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39) [atlassian-plugins-servlet-4.5.1.jar:?]
	at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58) [atlassian-plugins-servlet-4.5.1.jar:?]
	at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [?:?]
```

I found this is due to this cas client parsing xml format response,  but my company cas server return the json data.
I want to know if this client support the json parsing,  and how to configure json parsing ? ❓ 

thanks.

**Comment by njodessit** [comment]
Hi! Have you tried CAS 3.0 protocol? See https://github.com/apereo/java-cas-client/pull/212

org.jasig.cas.client.validation.json.Cas30JsonProxyReceivingTicketValidationFilter
